### ISSUE TITLE
feature/seller-browse-post-manage

### ISSUE THREAD

**Issue by oumbarry** [SOEN-341-Project/Group-P-soen341project2022#14]
## Epic: (16 points)
As a seller I can browse items, post items to the application, and manage their virtual storefront.

## Feature Requirements
- Seller can browse items
- Seller can post items to be sold 
   - Input item information in a form
   - Seller can edit the quantity of each item
- Seller can view and managed their virtual storefront containing their items informations

## Sub-tasks (sub-issues)
- [x] #18 **(4 points)**
- [x] #59  **(7 points)**
- [x] #57 **(5 points)**

**Comment by Adamo-O** [comment]
All sub tasks have been completed, this epic is also complete!
