### ISSUE TITLE
feature/title-related-to-associated-issue

### ISSUE THREAD

**Issue by ricks021** [SOEN-341-Project/Group-P-soen341project2022#20]
## Brief Description
Login page and registration page

## Feature Requirements
-  Registration page should have the following option ( admin, seller, buyer)
-  The registration info should be different between the admin and seller and buyer( different info ask)
-  buyer: e-mail, name || payment info?
-  seller: e-mail, name, business || Should we ask them bank accounts?

## Sub-tasks (sub-issues)
- [ ] #issue-number1
- [ ] #issue-number2

# Additional context

**Comment by aspyridakos** [comment]
This is not an appropriate title for an issue (its says nothing about what feature is being requested): 
![image](https://user-images.githubusercontent.com/71853151/151021619-f5e7444a-7811-4b72-bd28-dc60d023db2c.png)

**Comment by aspyridakos** [comment]
Too many labels, only `Epic 1 - Login/Sign up` and `frontend` are relevant here.
![image](https://user-images.githubusercontent.com/71853151/151021819-fcda4b37-8e25-464c-9923-e30632949ad2.png)

**Comment by aspyridakos** [comment]
As a general tip, leave issues unassigned unless someone is actively working on it or will be in the very near future. Assigning too early makes progress tracking needlessly difficult.

**Comment by aspyridakos** [comment]
@ricks021 
If you take a look in the issues (or projects board) section of Github, all the project epics had already been created prior to this issue being made. I've left some comments as future reference to help you with issue creation later but seeing as this issue is a duplicate, I will be closing it.
