### ISSUE TITLE
feature/change-default-mui-theme

### ISSUE THREAD

**Issue by Adamo-O** [SOEN-341-Project/Group-P-soen341project2022#43]
## User Story: (3 points)
As a user I want to be able to view all website content with a consistent theme.

## Brief Description
Overwrite the default MUI theme to change the font and colours globally.

## Feature Requirements
- Research MUI Typography overwriting
- Change default font to desired fonts in index.css (see `body font-family` and `@font-face`)
- Change default color scheme to match desired theme colors

## Risks
- Client may request for different themes to the website content.

## Additional Context
Check out [this StackOverflow post](https://stackoverflow.com/questions/48319372/changing-font-family-of-all-mui-components) which might help.

**Comment by aspyridakos** [comment]
Applied global css styles to page instead.
